sudo: required
services:
  - docker

before_install:
  - docker build -t jnelson62/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jnelson62/react-test npm test

after_success:
  - docker build -t jnelson62/multi-client ./client
  - docker build -t jnelson62/multi-nginx ./nginx
  - docker build -t jnelson62/multi-server ./server
  - docker build -t jnelson62/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push jnelson/multi-client
  - docker push jnelson/multi-nginx
  - docker push jnelson/multi-server
  - docker push jnelson/multi-worker